version: "3.8"
services:
  api:
    build: .
    image: vip-office:master
    ports:
      - 6060:6060
    env_file:
      - .env

  db:
    image: postgres:15.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vipoffice
    volumes:
      - ./db-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0.11
    ports:
      - 6379:6379
    volumes:
      - ./db-redis:/data

